spring:
  application:
    name: Springboot-Mybatis
  datasource: # 配置 druid 数据连接池
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ssm_crud?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 11111
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml  # 配置mybatis的mapper文件位置

# 设置日志级别
logging:
  level:
    org.example.mapper: debug
    org.example.test: debug